### ISSUE TITLE
你是重新训练生成的ckpt模型，还是将yolov3.weights转换为ckpt模型？

### ISSUE THREAD

**Issue by GitEasonXu** [raytroop/YOLOv3_tf#3]
Github上有yolov3.weights to Keras模型的代码，但是一直找不到Tensorflow模型的实现，实在感谢。
如果我想要使用预训练模型进行再训练应该如何进行？还望指点。

**Comment by raytroop** [comment]
I **DON'T** really convert darknet weights to tensorflow ckt, instead extract feature extractor weights [darknet53.conv.74](darknet53.conv.74) format of darknet and save it as npz using `save_npz.py` (modified from [yad2k](https://github.com/allanzelener/YAD2K/blob/master/yad2k.py)) This way, tensorflow weights can be initialized with them. I use `train_net.py` to train the following neural network(head and detector), feature extractor is frozen at the time.

**Comment by GitEasonXu** [comment]
谢谢你的回复,
